### ISSUE TITLE
Nummeric user ID for linking?

### ISSUE THREAD

**Issue by poVoq** [nextcloud/user_sql#108]
In the database setup I have (Mattermost) the users are represented both by an user name and a nummeric ID.

Setting up the normal users via the username is really easy, but the groups (teams in Mattermost) are linked through the nummeric id and thus it is not possible to use the user names for login and the same time the IDs for linking the groups.

As this seems to be a common system, it would be nice if an additional field could be added that allows linking such systems in the GUI easily.

Thanks!

**Comment by schniepp** [comment]
I have the same problem in phpbb3. Would be nice to get this to work!
I'll try some hacking if I find some extra time...

**Comment by poVoq** [comment]
Its possible to make an SQL view, but native support in the app would be nice.

**Comment by mlojewski-me** [comment]
I can add ID columns to both User, Group tables, then add User ID, Group ID columns to User group table and if all of these columns are set use them to link these tables instead of using Username, Group name columns.

**Comment by schniepp** [comment]
@mlojewski-me: wow, that would be terrific!

**Comment by palmtown** [comment]
Hello,

I believe your underlying issue was similar to mine in the since that I needed to separate the uid and the username columns so that I can allow my users to login by email, however, use a different column for the uid.  

I modified the code and submitted a pull request at https://github.com/nextcloud/user_sql/pull/122.  I tested it and works fine.  Once applied, you can go to Admin >> Settings >> SQL Backends >> User table and specify the UID and the Username columns.

Till it has been merged, you can test it out by cloning https://github.com/palmtown/user_sql/.  Let me know how it works out.

**Comment by mlojewski-me** [comment]
I merged the PR and make some changes which are on develop branch, I will release new  version pretty soon
