### ISSUE TITLE
Support Nextcloud 25

### ISSUE THREAD

**Issue by dregad** [nextcloud/user_sql#188]
Hello @mlojewski-me 

It would be nice, if this very useful App could be updated and a new Release published with official support for Nextcloud 25.

Background: I had no choice but to upgrade Nextcloud as my provider is forcing me to switch to PHP 8, and this is the only app that was not compatible. 

I am currently running it as "untested", so far with no noticeable issues.

Thanks in advance !

**Comment by spacefreak86** [comment]
Hello together

I agree, I also use this plugin in my environment in conjunction with my Postfix installation to give all my mail users access to my Nextcloud instance. Unfortunately, I am stuck with NC 22 (already unmaintained) because I currently don't have an alternative to this plugin.

Thanks in advance from we as well.

PS: if there is anything I can help with to make this happen, just let me know

**Comment by spacefreak86** [comment]
Hello @Bakaras 
Thank you for the information. Currently, I am using this fork of the user_sql repo, which seems to be patched to be compatible with NC25, maybe it helps you too:
https://github.com/rotdrop/user_sql
