### ISSUE TITLE
Remove deprecated hashing algorithm

### ISSUE THREAD

**Issue by sysmoh** [nextcloud/user_sql#27]
Hello,
I noticed that this app supports some deprecated hashing algorithm, like MD5 and SHA1, which are proven not secure anymore. Wouldn't it be better to remove them from the list?
Best regards

**Comment by mlojewski-me** [comment]
Right now I work on new version. I'm trying to redesign the app and remove chaos from the code.
Basically I don't think removing features is a good idea because some "lazy" users can still use them, as the app don't force users to use those hashes, it's their choice. Maybe add some comment/warning would be a good compromise

**Comment by sysmoh** [comment]
@mlojewski-me glad to hear that thanks a lot! Do you have any idea when it will be released?

**Comment by mlojewski-me** [comment]
I need about 2 weeks to finish then I will leave it in develop branch for testing and feedbacks.
