### ISSUE TITLE
Login with email address fails if local-part has a dot

### ISSUE THREAD

**Issue by crifi** [nextcloud/user_sql#58]
Nextcloud Version: 13.0.5
user_sql Version: master branch

I have observed a strange bug in this module on the login process.

## Szenario:
User A has username test1 and email address test@example-domain.com in my external database.
User B has username test2 and email address a.test@example-domain.com in my external database.

So the only difference is that the local-part of user B's email address contains a additional char plus a dot sign.

## Problem:
Both users can login with username and password.
User A can also login with email address, but not user B.

**Comment by karlja** [comment]
I have seen a similar behavior, where the login with email fails because the `$users = $this->userManager->getByEmail($user);` in LoginController::tryLogin() fails (`if (count($users) === 1) {`), because 2 elements are returned and it is therefore not unique (one seems to be an additional empty element):

```
Array
(
    [0] => 
    [1] => OC\User\User Object
        (...)
)
```

**Comment by mlojewski-me** [comment]
I looked at:
https://github.com/nextcloud/server/blob/master/core/Controller/LoginController.php#tryLogin

And the userId is taken from:
$users = $this->userManager->getByEmail($user);
->
$userIds = $this->config->getUsersForUserValue('settings', 'email', $email);

So I think if you want to login with email - first the email has to be synchronized with nextcloud, because is is not taken from external database. Also the email has to be unique.

```
// list emails in db
select * from oc_preferences where appid = 'settings' and configkey = 'email';
// list emails count in db
select count(configvalue), configvalue from oc_preferences where appid = 'settings' and configkey = 'email' group by configvalue order by 1 desc;
```
